import React, { useState } from "react";
import GenreDisplay from "./GenreDisplay";

const Genre = ({ genre }) => {
  return <GenreDisplay currentGenre={genreObject[`${genre}`]} />;
};

export default Genre;

let genreObject = {
  fantasy: {
    pageTitle: "Fantasy",
    genreHeading: "Step into the Realm of Wonders 🏰",
    genreDiscription:
      "In a world where magic lingers in the air, heroes and mythical creatures await those daring enough to venture beyond the veil of the ordinary. From enchanted forests to ancient kingdoms, the realms of fantasy invite you to escape the mundane and enter lands where anything is possible. Journey through epic tales of wizards, dragons, and forgotten worlds, where the only limit is your imagination. Prepare yourself, for the adventure of a lifetime lies just beyond this page.....",
    genreColor: "#C9E9D2",
    genreTopPicksHeading: "Epic Journeys Await: Must-Read Fantasy Adventures",
    genreTopPicks: [
      {
        bookCover: "/harry-potter.jpg",
        title: "Harry Potter",
        writer: "J.K. Rowling",
        genre: "Fantasy",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/hobbit.jpg",
        title: "The Hobbit",
        writer: "J.R.R. Tolkien",
        genre: "Fantasy",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/got.jpg",
        title: "A Game of Thrones",
        writer: "George R.R. Martin",
        genre: "Fantasy",
        rating: "4.4 ⭐️",
      },
      {
        bookCover: "/court-of-thorns-and-roses.jpg",
        title: "A Court of Thorns and Roses",
        writer: "Sarah J. Maas",
        genre: "Fantasy",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/six-of-crows.jpg",
        title: "Six of Crows",
        writer: "Leigh Bardugo",
        genre: "Fantasy",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/name-of-the-wind.jpg",
        title: "The Name of the Wind",
        writer: "Patrick Rothfuss",
        genre: "Fantasy",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/final-empire.jpg",
        title: "The Final Empire",
        writer: "Brandon Sanderson",
        genre: "Fantasy",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/the-lightning-thief.jpg",
        title: "The Lightning Thief",
        writer: "Rick Riordan",
        genre: "Fantasy",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/cruel-prince.jpg",
        title: "The Cruel Prince",
        writer: "Holly Black",
        genre: "Fantasy",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/shadow-and-bone.jpg",
        title: "Shadow and Bone",
        writer: "Leigh Bardugo",
        genre: "Fantasy",
        rating: "4 ⭐️",
      },
    ],
  },
  horror: {
    pageTitle: "Horror",
    genreHeading: "Enter if You Dare 👻",
    genreDiscription:
      "Darkness awaits in places where shadows whisper, and unseen terrors lie just beyond your sight. The horror genre calls to the brave and curious, those who aren’t afraid to confront the unknown. Here, twisted tales of haunting spirits, cursed places, and primal fears take hold. Step carefully and prepare for a journey through stories that chill, disturb, and leave you looking over your shoulder long after you close the book.....",
    genreColor: "#DBB5B5",
    genreTopPicksHeading: "Fearful Favorites: Essential Horror Reads",
    genreTopPicks: [
      {
        bookCover: "/shinning.jpg",
        title: "The Shinning",
        writer: "Stephen King",
        genre: "Horror",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/dracula.jpg",
        title: "Dracula",
        writer: "Bram Stoker",
        genre: "Horror",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/haunting-of-hill-house.jpg",
        title: "The Haunting of Hill House",
        writer: "Shirley Jackson",
        genre: "Horror",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/mexican-gothic.jpg",
        title: "Mexican Gothic",
        writer: "Silvia Moreno",
        genre: "Horror",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/exorcist.jpg",
        title: "The Exorcist",
        writer: "William Peter Blatty",
        genre: "Horror",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/coraline.jpg",
        title: "Coraline",
        writer: "Neil Gaiman",
        genre: "Horror",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/only-good-indians.jpg",
        title: "The Only Good Indians",
        writer: "Stephen Graham Jones",
        genre: "Horror",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/tender-is-the-flesh.jpg",
        title: "Tender Is the Flesh",
        writer: "Agustina Bazterrica",
        genre: "Horror",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/bird-box.jpg",
        title: "Bird Box",
        writer: "Josh Malerman",
        genre: "Horror",
        rating: "4.4 ⭐️",
      },
      {
        bookCover: "/heart-shaped-box.jpg",
        title: "Heart-Shaped Box",
        writer: "Joe Hill",
        genre: "Horror",
        rating: "4.3 ⭐️",
      },
    ],
  },
  mystery: {
    pageTitle: "Mystery",
    genreHeading: "Unlock the Secrets Within 🔎",
    genreDiscription:
      "Welcome to the world of hidden clues, elusive suspects, and thrilling twists. Mystery beckons you to follow a trail of breadcrumbs, to decipher cryptic puzzles and uncover secrets that others would rather keep buried. With every turn of the page, suspense mounts, and revelations loom in the shadows. Put on your detective hat and embark on an adventure where every clue brings you closer to the truth.....",
    genreColor: "#FFC6AC",
    genreTopPicksHeading: "Unravel the Secrets: Top Mystery Novels",
    genreTopPicks: [
      {
        bookCover: "/murder-orient-express.jpg",
        title: "Murder on the Orient Express",
        writer: "Agatha Christie",
        genre: "Mystery",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/dragon-tattoo.jpg",
        title: "The Girl with the Dragon Tattoo",
        writer: "Stieg Larsson",
        genre: "Mystery",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/gone-girl.jpg",
        title: "Gone Girl",
        writer: "Gillian Flynn",
        genre: "Mystery",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/girl-on-train.jpg",
        title: "The Girl on the Train",
        writer: "Paula Hawkins",
        genre: "Mystery",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/da-vinci-code.jpg",
        title: "The Da Vinci Code",
        writer: "Dan Brown",
        genre: "Mystery",
        rating: "4.4 ⭐️",
      },
      {
        bookCover: "/silent-patient.jpg",
        title: "The Silent Patient",
        writer: "Alex Michaelides",
        genre: "Mystery",
        rating: "4.6 ⭐️",
      },
      {
        bookCover: "/one-of-us-lying.jpg",
        title: "One of Us Is Lying",
        writer: "Karen M. McManus ",
        genre: "Mystery",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/inheritance-games.jpg",
        title: "The Inheritance Games",
        writer: "Jennifer Lynn Barnes",
        genre: "Mystery",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/cuckoo-calling.jpg",
        title: "The Cuckoo's Calling",
        writer: "Robert Galbraith",
        genre: "Mystery",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/angels-and-demons.jpg",
        title: "Angels and Demons",
        writer: "Dan Brown",
        genre: "Mystery",
        rating: "4.4 ⭐️",
      },
    ],
  },
  romance: {
    pageTitle: "Romance",
    genreHeading: "Find Love in Every Chapter 💖",
    genreDiscription:
      "Here lies a world of tender connections, stolen glances, and hearts intertwined. Romance transports us to places where love blossoms in unexpected moments and passion defies all odds. From chance encounters to timeless bonds, these stories of the heart promise warmth, laughter, and the undeniable joy of love’s journey. Lose yourself in tales that celebrate the beauty of human connection and the thrill of happily-ever-after.....",
    genreColor: "#FF9B9B",
    genreTopPicksHeading: "Heartfelt Tales: Romance to Swoon Over",
    genreTopPicks: [
      {
        bookCover: "/beach-read.jpg",
        title: "Beach Read",
        writer: "Emily Henry",
        genre: "Romance",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/hating-game.jpg",
        title: "The Hating Game",
        writer: "Sally Thorne",
        genre: "Romance",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/twilight.jpg",
        title: "Twilight",
        writer: "Stephenie Meyer",
        genre: "Romance",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/kiss-quotient.jpg",
        title: "The Kiss Quotient",
        writer: "Helen Hoang",
        genre: "Romance",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/ugly-love.jpg",
        title: "Ugly Love",
        writer: "Colleen Hoover",
        genre: "Romance",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/me-before-you.jpg",
        title: "Me Before You",
        writer: "Jojo Moyes",
        genre: "Romance",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/deal.jpg",
        title: "The Deal",
        writer: "Elle Kennedy",
        genre: "Romance",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/selection.jpg",
        title: "The Selection",
        writer: "Kiera Cass",
        genre: "Romance",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/twisted-love.jpg",
        title: "Twisted Love",
        writer: "Ana Huang",
        genre: "Romance",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/love-theoretically.jpg",
        title: "Love, Theoretically",
        writer: "Emily Henry ",
        genre: "Romance",
        rating: "4.2 ⭐️",
      },
    ],
  },
  scifi: {
    pageTitle: "Sci-fi",
    genreHeading: "Explore the Cosmos and Beyond 👽",
    genreDiscription:
      "Step into a future filled with incredible technologies, alien worlds, and realities beyond our own. Science fiction invites you to dream of what’s possible, from intergalactic adventures to mind-bending discoveries at the edge of science. Enter a realm where human imagination pushes the boundaries of existence, and where the wonders of the universe await. Prepare for journeys that defy the laws of nature and explore the mysteries of the unknown.....",
    genreColor: "#D2E0FB",
    genreTopPicksHeading: "Beyond the Stars: Sci-Fi Classics You’ll Love",
    genreTopPicks: [
      {
        bookCover: "/dune.jpg",
        title: "Dune",
        writer: "Frank Herbert",
        genre: "Sci-fi",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/enders-game.jpg",
        title: "Ender's Game",
        writer: "Orson Scott Card",
        genre: "Sci-fi",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/guide-to-galaxy.jpg",
        title: "The Hitchhiker’s Guide to the Galaxy",
        writer: "Douglas Adams",
        genre: "Sci-fi",
        rating: "4.2 ⭐️",
      },
      {
        bookCover: "/martian.jpg",
        title: "The Martian",
        writer: "Andy Weir",
        genre: "Sci-fi",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/ready-player-one.jpg",
        title: "Ready Player One",
        writer: "Ernest Cline",
        genre: "Sci-fi",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/f451.jpg",
        title: "Fahrenheit 451",
        writer: "Ray Bradbury",
        genre: "Sci-fi",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/1984.jpg",
        title: "1984",
        writer: "George Orwell",
        genre: "Sci-fi",
        rating: "4.7 ⭐️",
      },
      {
        bookCover: "/hunger-games.jpg",
        title: "The Hunger Games",
        writer: "Suzanne Collins",
        genre: "Sci-fi",
        rating: "4.4 ⭐️",
      },
      {
        bookCover: "/foundation.jpg",
        title: "Foundation",
        writer: "Isaac Asimov",
        genre: "Sci-fi",
        rating: "4.6 ⭐️",
      },
      {
        bookCover: "/android-sheep.jpg",
        title: "Do Androids Dream of Electric Sheep?",
        writer: "Philip K. Dick",
        genre: "Sci-fi",
        rating: "4.1 ⭐️",
      },
    ],
  },
  thriller: {
    pageTitle: "Thriller",
    genreHeading: "Brace Yourself for Heart-Pounding Suspense ⏰",
    genreDiscription:
      "Get ready for a whirlwind of high-stakes drama, gripping twists, and edge-of-your-seat tension. In the thriller world, danger lurks around every corner, and adrenaline flows with every word. Plunge into stories of daring escapes, dangerous encounters, and relentless pursuits. With each page turn, suspense mounts, leading you to moments of breathless anticipation and heart-racing excitement. Are you ready for the thrill???",
    genreColor: "#FFF6E3",
    genreTopPicksHeading: "Edge of Your Seat: Gripping Thriller Must-Reads",
    genreTopPicks: [
      {
        bookCover: "/verity.jpg",
        title: "Verity",
        writer: "Colleen Hoover",
        genre: "Thriller",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/housemaid.jpg",
        title: "The Housemaid",
        writer: "Freida McFadden",
        genre: "Thriller",
        rating: "4.5 ⭐️",
      },
      {
        bookCover: "/sharp-objects.jpg",
        title: "Sharp Objects",
        writer: "Gillian Flynn",
        genre: "Thriller",
        rating: "4.1 ⭐️",
      },
      {
        bookCover: "/guests-list.jpg",
        title: "The Guest List",
        writer: "Lucy Foley",
        genre: "Thriller",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/good-girl-murder.jpg",
        title: "The Good Girl's Guide to Murder",
        writer: "Holly Jackson",
        genre: "Thriller",
        rating: "4.4 ⭐️",
      },
      {
        bookCover: "/women-window.jpg",
        title: "The Women in the Window",
        writer: "A.J. Finn",
        genre: "Thriller",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/dark-matter.jpg",
        title: "Dark Matter",
        writer: "Blake Crouch",
        genre: "Thriller",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/behind-closed-doors.jpg",
        title: "Behind Closed Doors",
        writer: "B.A. Paris",
        genre: "Thriller",
        rating: "4 ⭐️",
      },
      {
        bookCover: "/and-then-there-were-none.jpg",
        title: "And Then There Were None",
        writer: "Agatha Christie",
        genre: "Thriller",
        rating: "4.3 ⭐️",
      },
      {
        bookCover: "/pretty-girls.jpg",
        title: "Pretty Girls",
        writer: "Karin Slaughter",
        genre: "Thriller",
        rating: "4.1 ⭐️",
      },
    ],
  },
};
